version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.kodein.di:kodein-di-conf-jvm
    versions:
    - 7.2.0
    - 7.3.0
    - 7.3.1
    - 7.4.0
  - dependency-name: org.kodein.di:kodein-di-framework-ktor-server-jvm
    versions:
    - 7.2.0
    - 7.3.0
    - 7.3.1
    - 7.4.0
  - dependency-name: org.postgresql:postgresql
    versions:
    - 42.2.18
    - 42.2.19
  - dependency-name: org.testcontainers:testcontainers
    versions:
    - 1.15.1
    - 1.15.2
  - dependency-name: org.testcontainers:postgresql
    versions:
    - 1.15.1
    - 1.15.2
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-core
    versions:
    - 1.4.2-native-mt
  - dependency-name: io.github.microutils:kotlin-logging
    versions:
    - 1.12.0
  - dependency-name: org.junit.jupiter:junit-jupiter
    versions:
    - 5.7.0
