language: java

cache:
  directories:
    - $HOME/.m2
    - $TRAVIS_BUILD_DIR/tmp

env:
  - DO_NOT_COMMIT_CONTAINER=yes
  - POSTGIS_LOW_MEM=yes

before_install:
  - cp config.dist.json config.json
  - cp logback.travis.xml src/main/resources/logback-test.xml

services:
  - docker

script:
  - travis_wait 30 mvn test -B

after_success:
  - bash <(curl -s https://codecov.io/bash) -t e6313f6d-15f0-4b4d-be4b-37455c2b0ad6
