# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
executorType: machine

jobs:
  build-and-test:
    machine:
      image: ubuntu-1604:201903-01

    working_directory: ~/repo

    environment: &environment
      DO_NOT_COMMIT_CONTAINER: yes
      POSTGIS_LOW_MEM: yes
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m


    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Package
          command: |
            cp config.dist.json config.json
            cp logback.travis.xml src/main/resources/logback-test.xml
            cp logback.travis.xml src/main/resources/logback.xml
            mvn package -DskipTests

      # run tests!
      - run:
          name: Test
          command: |
            mvn test
            mkdir artifacts
            cp target/*.jar artifacts

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - persist_to_workspace:
          root: ~/repo
          paths:
            - target
            - config.json

      - store_artifacts:
          path: ~/repo/artifacts

